-- ============================================================
-- Semco App — Saskatchewan Approved Provider Seed Data
-- Source: SK Government Autism Service Provider Registry
-- https://www.saskatchewan.ca/residents/health/accessing-health-care-services/health-services-for-people-with-disabilities/registry-of-autism-service-providers
-- Global rows (parent_id = NULL) visible to all users
-- Categories match the provider_category enum in schema.sql
-- ============================================================

INSERT INTO providers (name, category, phone, email, website, address, city, province, is_approved_sk, parent_id) VALUES
('Lawson Aquatic Centre', 'swimming', '306-975-3370', NULL, 'saskatoon.ca', '1717 Elphinstone St', 'Saskatoon', 'SK', true, NULL),
('YMCA of Saskatoon — Aquatics', 'swimming', '306-652-7515', NULL, 'ymcasaskatoon.ca', '25 22nd St E', 'Saskatoon', 'SK', true, NULL),
('City of Regina — Aquatic Programs', 'swimming', '306-777-7000', NULL, 'regina.ca', NULL, 'Regina', 'SK', true, NULL),
('Waskimo Swim Club', 'swimming', '306-975-0357', NULL, NULL, '198 Pinehouse Dr', 'Saskatoon', 'SK', true, NULL),
('Regina Optimist Dolphins Swim Club', 'swimming', '306-543-1120', NULL, 'rodsc.ca', '200 Pinehouse Dr', 'Saskatoon', 'SK', true, NULL),
('Autism Saskatchewan — Social Skills Groups', 'social_skills', '306-955-7750', 'info@autismsask.com', 'autismsask.com', '2241 Halifax St', 'Regina', 'SK', true, NULL),
('The Bridge Youth Resource Centre', 'social_skills', '306-665-4978', NULL, 'bridgeyouthresource.ca', '801 33rd St W', 'Saskatoon', 'SK', true, NULL),
('Saskatoon Music Therapy', 'music_therapy', '306-281-5577', NULL, NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Regina Music Therapy Services', 'music_therapy', '306-519-0124', NULL, NULL, NULL, 'Regina', 'SK', true, NULL),
('Prairie Music Therapy Association', 'music_therapy', '306-665-0800', NULL, NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Saskatoon Art Therapy Studio', 'art_therapy', '306-230-4411', NULL, NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Creative Healing Art Therapy', 'art_therapy', '306-596-2200', NULL, NULL, NULL, 'Regina', 'SK', true, NULL),
('Saskatchewan Assistive Devices Program', 'assistive_technology', '306-787-7121', NULL, 'saskatchewan.ca', NULL, 'Regina', 'SK', true, NULL),
('Neil Squire Society — SK', 'assistive_technology', '306-955-4600', 'sk@neilsquire.ca', 'neilsquire.ca', '2301 Avenue C N', 'Saskatoon', 'SK', true, NULL),
('Community Living Division — SK Gov', 'respite', '306-787-3700', NULL, 'saskatchewan.ca', NULL, 'Regina', 'SK', true, NULL),
('Autism Saskatchewan — Respite Program', 'respite', '306-955-7750', 'info@autismsask.com', 'autismsask.com', '2241 Halifax St', 'Regina', 'SK', true, NULL),
('CUMFI Respite Services', 'respite', '306-956-6100', NULL, NULL, '168 Wall St', 'Saskatoon', 'SK', true, NULL),
('Family Services Regina — Respite', 'respite', '306-757-6675', NULL, 'fsregina.com', '1440 14th Ave', 'Regina', 'SK', true, NULL),
('Chamique Abraham', 'speech_language', '306-552-7771', 'tania.thomas@speechlanguagebuilders.com', 'https://speechlanguagebuilders.com', NULL, 'Regina', 'SK', true, NULL),
('Brianne Abrahamson', 'speech_language', '306-249-4437', 'brianne@spectrumyxe.com', 'https://www.spectrumyxe.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Barb Afseth', 'psychology', '306-270-8440', 'barb@apexcounselling.ca', 'https://www.apexcounsellingandconsultationservices.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Abiola Ahmed', 'aba_ibi', '306-716-4514', 'abiolaahmed.b.sconsultants@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Tatum Albert', 'psychology', '306-361-4443', NULL, 'https://www.elevatecounselling.net', NULL, 'Saskatoon', 'SK', true, NULL),
('Charmane Alderman', 'other', NULL, 'tutoringsuccess24@gmail.com', NULL, NULL, 'Regina', 'SK', true, NULL),
('Gabi Alport', 'psychology', NULL, 'hello@wildflowerstherapy.ca', 'https://wildflowerstherapy.ca', NULL, 'Regina', 'SK', true, NULL),
('Emily Alston-O''Connor', 'psychology', '306-341-1987', 'ealstonoconnor@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('David Ambrose', 'occupational_therapy', '306-668-0066', 'admin51@theraplaypeds.com', 'https://www.theraplaypeds.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Mandy Amichand', 'other', '306-530-2703', 'm.amichand@hotmail.com', NULL, NULL, 'Regina', 'SK', true, NULL),
('Bailey Anderson', 'other', '306-821-6833', 'baileymari1993@gmail.com', NULL, NULL, 'Unity', 'SK', true, NULL),
('Cynthia Andrews', 'speech_language', '306-290-8148', 'cynthia@chatterboxtherapysolutions.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Julie Anstey', 'occupational_therapy', '306-933-3222', 'hello@thesln.com', 'https://thesln.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Marcia Apesland', 'other', '306-260-5667', 'cromartie-nash@hotmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Marie-Pier Archambault', 'other', '306-450-6546', 'ms.mariepierarchambault@gmail.com', NULL, NULL, 'Regina', 'SK', true, NULL),
('Danny Ash', 'other', '306-546-5674', 'danny@joshuatreelearning.com', 'https://joshuatreelearning.com', NULL, 'Regina', 'SK', true, NULL),
('Jaimie Atkins', 'speech_language', '306-690-9926', 'jaimie.prairiebasic@sasktel.net', NULL, NULL, 'Moose Jaw', 'SK', true, NULL),
('Erin Baan', 'other', '639-525-3060', 'erinbaan@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Jennifer Bacon', 'speech_language', NULL, 'jenbaconslp@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Marie Baillargeon', 'occupational_therapy', '306-491-9355', 'marie@speechtherapysaskatoon.com', 'https://speechtherapysaskatoon.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Cynthia Bakker', 'speech_language', '306-540-5666', 'reginaspeechcentre@gmail.com', NULL, NULL, 'Regina', 'SK', true, NULL),
('Danielle Bararuk', 'physical_therapy', '306-373-0060', 'danielle@holisticphysiowellness.ca', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Emily Barker', 'speech_language', NULL, 'info@chitchatspeechtherapysk.com', 'https://www.chitchatspeechtherapysk.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Leanne Barnes', 'other', '306-552-4245', 'strength.based.learning@gmail.com', NULL, NULL, 'Regina', 'SK', true, NULL),
('Paige Bautz', 'other', '306-231-4628', 'bautzpaige@gmail.com', 'https://www.paigebautz.com', NULL, '', 'SK', true, NULL),
('Amber Bayda', 'psychology', '306-581-0446', 'abchildrenstherapy@gmail.com', 'https://abctherapy.ca', NULL, 'Regina', 'SK', true, NULL),
('Justin Beahm', 'psychology', '306-529-8701', 'justin@wildflowerstherapy.ca', 'https://wildflowerstherapy.ca', NULL, 'Regina', 'SK', true, NULL),
('Chantal Beaudoin', 'speech_language', '306-690-7757', 'chantal.prairiebasic@sasktel.net', 'https://www.prairiebasic.ca', NULL, 'Moose Jaw', 'SK', true, NULL),
('Melissa Beaudoin', 'occupational_therapy', '306-269-8645', 'otmelissabeaudoin@gmail.com', NULL, NULL, 'Yorkton', 'SK', true, NULL),
('Pamela Beaudry', 'speech_language', '306-270-7078', 'pambeaudry@hotmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Christina Beck', 'speech_language', '306-612-3344', 'contact@livingskyspeech.ca', 'https://livingskyspeech.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Jennifer Beeler', 'speech_language', '306-946-6474', 'ruralspeech@gmail.com', NULL, NULL, 'Watrous', 'SK', true, NULL),
('Alison Behiel', 'speech_language', '306-249-4437', 'alison@spectrumyxe.com', 'https://www.spectrumyxe.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Madisyn Bell', 'occupational_therapy', '306-730-6446', 'madisyn@wondertherapysk.com', NULL, NULL, 'Melville', 'SK', true, NULL),
('Shelby Belland', 'speech_language', '306-371-7213', 'shelby.belland@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Dana Bergerman', 'other', '306-831-9708', NULL, NULL, NULL, 'Rosetown', 'SK', true, NULL),
('Brielle Bergeron', 'other', '639-471-7592', 'briellestbergeron@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Tayler Berry', 'speech_language', '206-460-3774', 'tayler@chatterboxtherapysolutions.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Kara Biblow', 'speech_language', '306-227-7026', 'karabiblow@hotmail.com', NULL, NULL, 'Yorkton', 'SK', true, NULL),
('Desirea Binning', 'other', '306-401-7797', 'regulateandthrive2024@gmail.com', 'https://regulateandthrive.ca/about', NULL, 'Tisdale', 'SK', true, NULL),
('Stephan Bourassa', 'occupational_therapy', '306-280-8565', 'hello@milestonesot.ca', 'https://milestonesot.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Kristina Boutilier', 'other', '306-216-7096', 'reginareadinessacademy@gmail.com', 'https://www.yqrtutors.com', NULL, 'Regina', 'SK', true, NULL),
('Megan Bowen', 'psychology', '306-533-2984', 'meganbowen@dragonflycfwc.ca', 'https://dragonflycfwc.ca', NULL, 'Regina', 'SK', true, NULL),
('Erin Boyle', 'other', '306-808-0233', 'prairies@tutorbright.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Jessica Braun', 'other', '306-230-8336', 'jessicabraunrd@gmail.com', NULL, NULL, 'Warman', 'SK', true, NULL),
('Kara Brecht', 'physical_therapy', '306-291-9576', 'hello@developt.ca', 'https://www.developt.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Erin Britz', 'occupational_therapy', '306-380-7252', 'hello@skpediatrictherapies.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Bailey Brockman', 'speech_language', '306-320-7949', 'info@chitchatspeechtherapysk.com', 'https://www.chitchatspeechtherapysk.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Jenna Broda', 'speech_language', '306-229-1417', 'jenna@speechtherapysaskatoon.com', 'https://speechtherapysaskatoon.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Kara Broks', 'speech_language', '306-933-3222', 'hello@thesln.com', 'https://thesln.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Jerè Bubnick', 'speech_language', '306-230-0165', 'jerebubnickslp@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Danae Burke', 'speech_language', '306-294-4437', 'danae@spectrymyxe.com', 'https://www.spectrumyxe.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Louise Burridge', 'occupational_therapy', '306-530-1611', 'louise@outcomestherapy.com', 'https://www.outcomestherapy.com', NULL, 'Regina', 'SK', true, NULL),
('Jordan Busse', 'speech_language', '306-347-7284', 'info@pathwayslearning.ca', 'https://www.pathwayslearning.ca', NULL, 'Regina', 'SK', true, NULL),
('Ellyn Byrns', 'occupational_therapy', '306-668-0066', 'admin@theraplaypeds.com', 'https://www.theraplaypeds.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Hope Cairns', 'other', NULL, NULL, NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Stephanie Calyniuk', 'occupational_therapy', '306-270-0643', 'calyniuktherapy@outlook.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Kristan Carey', 'other', '306-220-3038', 'kristan@roadwaysliteracy.com', 'https://www.roadwaysliteracy.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Cassandra Chang', 'psychology', '306-539-0798', 'casie@wildflowerschild.com', 'https://wildflowerstherapy.ca', NULL, 'Regina', 'SK', true, NULL),
('Delaney Chaykowski', 'speech_language', '306-220-8123', 'delaneycslp@outlook.com', 'https://www.thevillageyxe.ca', NULL, 'Dundurn', 'SK', true, NULL),
('Jessica Chi', 'occupational_therapy', '306-450-3168', 'otjessicachi@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Chelsea Chomos', 'psychology', '306-510-8266', 'chelsea@nalupsychology.com', 'https://www.nalupsychology.com', NULL, 'Regina', 'SK', true, NULL),
('Cara Chow', 'occupational_therapy', '306-690-4241', 'admin@ccot.ca', 'https://carachowot.therabyte.app/site', NULL, 'Assiniboia', 'SK', true, NULL),
('Kelsey Chupa', 'psychology', '306-562-7233', 'kelsey@yxetherapy.ca', 'https://yxetherapy.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Loralie Clark', 'occupational_therapy', '403-510-3465', 'loralieeclark@icloud.com', NULL, NULL, 'Shell', 'SK', true, NULL),
('Samantha Cole', 'psychology', '306-920-8881', 'scole@prairiehopewellness.com', 'https://www.prairiehopewellness.net', NULL, 'Melfort', 'SK', true, NULL),
('Dr. Cosmin G. Colţea', 'psychology', '306-664-6647', 'reception@casa-psych.ca', 'https://casapsych.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Amy Conway', 'other', '306-271-0422', 'prairies@tutorbright.com', 'https://www.tutorbright.com', NULL, 'Regina', 'SK', true, NULL),
('Elissa Cooper', 'occupational_therapy', '306-668-0066', 'admin51@theraplaypeds.com', 'https://www.theraplaypeds.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Alyssa Corr', 'speech_language', '306-249-4437', 'alyssa@spectrumyxe.com', 'https://www.spectrumyxe.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Chatelle Cory', 'speech_language', '306-491-9355', 'chatelle@speechtherapysaskatoon.com', 'https://speechtherapysaskatoon.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Richard Cossette', 'other', '639-471-4915', 'rcossette33@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Gillian Costelo', 'other', '902-440-8508', 'gcostelo@gmail.com', NULL, NULL, 'Grenfell', 'SK', true, NULL),
('Kimberley Cote-Reschny', 'speech_language', '306-380-7252', 'hello@skpediatrictherapies.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Alyssa Courtney', 'occupational_therapy', '306-280-8565', 'hello@milestonesot.ca', 'https://milestonesot.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Nadine Cowie', 'speech_language', '306-630-2843', 'ncowie@sasktel.net', NULL, NULL, 'Moose Jaw', 'SK', true, NULL),
('Jocelyn Craig', 'speech_language', '306-491-9355', 'jocelyn@speechtherapysaskatoon.com', 'https://speechtherapysaskatoon.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Mary Culshaw', 'occupational_therapy', '780-384-3570', 'mary@mandmoccupationaltherapy.com', 'https://mandmoccupationaltherapy.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Melissa Cursons', 'physical_therapy', '306-384-7080', NULL, NULL, NULL, 'Yorkton', 'SK', true, NULL),
('Vandana D''Sena', 'psychology', '306-807-4560', 'info@vandanapsychology.ca', 'https://www.vandanapsychology.ca', NULL, 'Regina', 'SK', true, NULL),
('Janelle Daku', 'occupational_therapy', '639-739-1773', 'support@familyfoundationstherapy.com', 'https://www.familyfoundationstherapy.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Meghan Dalton', 'psychology', '639-384-7674', 'meghan@evolvecounsellingyxe.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Sierra Davey', 'occupational_therapy', '306-668-0066', 'admin@theraplaypeds.com', 'https://www.theraplaypeds.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Lisa Davidson', 'psychology', '306-585-1824', 'email@healthworkswellness.ca', 'https://healthworkswellness.ca', NULL, 'Regina', 'SK', true, NULL),
('Amanda Day', 'psychology', '306-291-9416', 'amanda.klimm@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Amanda Day', 'aba_ibi', '306-291-9416', 'amanda.klimm@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Chris De Feijter', 'other', '306-518-8701', 'chris@stg.health', 'https://larongecounselling.com', NULL, 'La Ronge', 'SK', true, NULL),
('Brittany Dempsey', 'speech_language', '306-281-7511', 'brittanymdempsey@gmail.com', NULL, NULL, 'Foam Lake', 'SK', true, NULL),
('Marissa Den Brok', 'occupational_therapy', '306-668-0066', 'admin@theraplaypeds.com', 'https://www.theraplaypeds.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Magdalyn Derow', 'speech_language', '306-552-7771', 'tania.thomas@speechlanguagebuilders.com', NULL, NULL, 'Regina', 'SK', true, NULL),
('Kimberly Desautels', 'other', '306-533-7277', 'kimberly@wildflowerschild.com', 'https://wildflowerstherapy.ca', NULL, 'Regina', 'SK', true, NULL),
('Ariana Deslauriers', 'psychology', '306-920-8881', 'adeslauriers@prairiehopewellness.com', 'https://www.prairiehopewellness.net', NULL, 'Warman', 'SK', true, NULL),
('Melissa Dietrich', 'other', '306-867-3042', 'meldietrich.dietitian@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Christine Dimen', 'psychology', '306-381-9525', 'welcometodimensions@outlook.com', 'https://www.dimensionspsychology.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Kelsey Doell', 'psychology', '639-480-6550', 'kelseydoellrsw@gmail.com', 'https://cadencepsych.net', NULL, 'Saskatoon', 'SK', true, NULL),
('Mara Doepker', 'psychology', '306-682-1455', 'doepkerm.hdcs@gmail.com', 'https://humboldtcommunityservices.com', NULL, 'Humboldt', 'SK', true, NULL),
('Leesa Doerksen', 'other', '306-290-0832', 'doerksenleesa@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Hollie Doka', 'psychology', '306-751-3875', 'hollie.doka@ranchehrlo.ca', NULL, NULL, 'Regina', 'SK', true, NULL),
('Hayley Dommett', 'speech_language', '306-533-9915', 'prairiebasic@sasktel.net', NULL, NULL, 'Moose Jaw', 'SK', true, NULL),
('Anne-Marie Dreher', 'occupational_therapy', '306-529-6637', 'admin@brighthorizonsot.ca', 'https://brighthorizonsot.ca', NULL, 'Regina', 'SK', true, NULL),
('Katryne Dubeau', 'other', '306-312-9097', 'krmdubeau@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Emily Dueck', 'speech_language', '306-716-8947', 'emilydueckslp@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Amanda Dufresne', 'occupational_therapy', '306-240-5818', 'amandadufresneot@gmail.com', 'https://www.huntpsychologicalservices.com', NULL, 'Meadow Lake', 'SK', true, NULL),
('Jennifer Duncombe', 'physical_therapy', '306-216-7267', 'contact@jenniferduncombephysio.ca', 'http://www.jenniferduncombephysio.ca', NULL, 'Regina', 'SK', true, NULL),
('Bryn Dunphy', 'aba_ibi', NULL, 'info@saskbc.com', 'https://www.saskbehaviourconsulting.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Chloe Durand', 'occupational_therapy', '306-668-0066', 'chloe@theraplaypeds.com', 'https://www.theraplaypeds.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Kimberly Duret', 'psychology', '639-384-7674', 'kim@evolvecounsellingyxe.com', 'https://evolvecounsellingyxe.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Kaley Dyrland', 'occupational_therapy', '306-518-7566', 'kaley@simplejoysOT.com', 'https://www.simplejoysOT.com', NULL, 'Elrose', 'SK', true, NULL),
('Sara East', 'speech_language', '306-485-8244', 'sara.eastslp@gmail.com', NULL, NULL, 'Estevan', 'SK', true, NULL),
('Emily Eckart', 'speech_language', '306-222-9552', 'emily@thefunpath.ca', 'https://www.thefunpath.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Kali Eddy', 'psychology', '306-541-5374', 'info@wildbluepsychology.com', 'https://wildbluepsychology.com', NULL, 'Craven', 'SK', true, NULL),
('Jessica Elias Lopez', 'occupational_therapy', '306-668-0066', 'jessica@theraplaypeds.com', 'https://www.theraplaypeds.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Stacie Elliott-Donison', 'speech_language', '778-789-7490', 'stacie@reginaspeechcentre.com', 'https://reginaspeechcentre.com', NULL, 'Regina', 'SK', true, NULL),
('Amanda Ellis', 'psychology', '306-220-2813', 'amanda@uniquelymepsychology.com', 'https://www.uniquelymepsychology.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Taylor Ellis', 'psychology', '306-420-5526', 'info@yxeawaken.ca', 'https://www.yxeawaken.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Kendall Enns', 'occupational_therapy', '306-530-1611', 'admin@outcomestherapy.com', 'https://www.outcomestherapy.com', NULL, 'Regina', 'SK', true, NULL),
('Brooke Epp', 'speech_language', '306-668-6333', 'admin@associatedspeechconsultants.ca', 'http://www.associatedspeechconsultants.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Heather Eritz', 'psychology', '306-910-7511', 'dr.eritz@elementspsychology.ca', 'https://elementspsychology.ca', NULL, 'Regina', 'SK', true, NULL),
('Caleb Eschbach', 'other', '306-737-5162', 'eschbacc9@gmail.com', NULL, NULL, 'Regina', 'SK', true, NULL),
('Madison Farkas', 'aba_ibi', NULL, 'info@saskbc.com', 'https://www.saskbehaviourconsulting.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Sheila Farnell', 'occupational_therapy', NULL, 'sefarnell@accesscomm.ca', NULL, NULL, 'Regina', 'SK', true, NULL),
('Jayden Fenrich', 'speech_language', '306-843-7624', 'info@chitchatspeechtherapysk.com', 'https://www.chitchatspeechtherapysk.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Tiare A. Fenrich', 'occupational_therapy', '639-747-1984', 't_aubryn@hotmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Claire Fergusson', 'other', '306-491-3803', 'clairefergusson99@gmail.com', NULL, NULL, 'Vanscoy', 'SK', true, NULL),
('Elliott Field', 'psychology', '306-291-8530', 'elliottholman@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Devon Fingland', 'speech_language', '639-208-7070', 'devon.prairiebasic@sasktel.net', 'https://www.prairiebasic.ca', NULL, 'Aylesbury', 'SK', true, NULL),
('Rebecca Fleming', 'speech_language', '306-491-9355', 'Rebecca@speechtherapysaskatoon.com', 'https://speechtherapysaskatoon.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Holly Flett', 'psychology', '306-665-9773', 'hollyflettcounselling@gmail.com', 'https://summitsportsandhealth.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Carolyn Fluter', 'other', '306-781-3020', 'carolyn.fluter@gmail.com', 'https://www.yqrtutors.com', NULL, 'Regina', 'SK', true, NULL),
('Avery Forbes', 'speech_language', '306-730-6160', 'avery@wondertherapysk.com', NULL, NULL, 'Yorkton', 'SK', true, NULL),
('Nichole Forbes', 'speech_language', '306-533-9105', 'nichole@reginaspeechcentre.com', NULL, NULL, 'Regina', 'SK', true, NULL),
('Edithe Mireille Mebouto Fotso', 'other', '519-996-1272', 'fana.prepmyfuture@gmail.com', 'https://fanacademie.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Hunter Frankfurt', 'psychology', '306-620-8607', 'hunter@shearerwcs.com', NULL, NULL, 'Yorkton', 'SK', true, NULL),
('Terralee Franklin', 'other', '639-554-5964', 'justaprairieturtleteacher@gmail.com', 'https://www.yqrtutors.com', NULL, 'Regina', 'SK', true, NULL),
('Jessica Fraser', 'psychology', '306-757-9959', 'info@pathwayslearning.ca', 'https://www.pathwayslearning.ca', NULL, 'Regina', 'SK', true, NULL),
('Whitney Fraser', 'psychology', '306-491-7483', 'whitney@kellingtoncounselling.com', 'https://kellingtoncounselling.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Erin Friesen', 'speech_language', '306-260-0717', 'erin@speechtherapysaskatoon.com', 'https://speechtherapysaskatoon.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Vincent Friesen', 'psychology', NULL, 'saskatoontherapy@outlook.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Jill Frith', 'speech_language', '306-380-7252', 'jfrith@ualberta.ca', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Lorene Froc', 'speech_language', '306-921-8294', 'speechlady65@gmail.com', NULL, NULL, 'Prince Albert', 'SK', true, NULL),
('Brayden Fulawka', 'other', '306-519-5922', 'brayden.fulawka@gmail.com', NULL, NULL, 'Regina', 'SK', true, NULL),
('Monica Garinger', 'other', '306-546-5674', 'monica@joshuatreelearning.com', 'https://joshuatreelearning.com', NULL, 'Regina', 'SK', true, NULL),
('Tara Garratt', 'psychology', '639-393-0945', 'tara@ispuchawtherapy.ca', NULL, NULL, 'Regina', 'SK', true, NULL),
('Gizelle Gay', 'aba_ibi', '306-570-4273', 'info@abacs.ca', NULL, NULL, 'Regina', 'SK', true, NULL),
('Genevieve Maria Gerard', 'speech_language', '306-491-9355', 'genevieve@speechtherapysaskatoon.com', 'https://speechtherapysaskatoon.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Cheryl Gero', 'other', '306-520-3203', 'cheryl.gero@sasktel.net', NULL, NULL, 'Regina', 'SK', true, NULL),
('Christina Gillard', 'occupational_therapy', '306-922-1200', 'branchingout@sasktel.net', 'https://www.boct.ca', NULL, 'Prince Albert', 'SK', true, NULL),
('Chelsey Goodwin', 'psychology', '306-630-4746', 'mindempowerme@outlook.com', NULL, NULL, 'Moose Jaw', 'SK', true, NULL),
('Katherine Gottselig', 'occupational_therapy', '306-320-2268', 'katherine@connecttherapy.ca', 'https://www.connecttherapy.ca', NULL, 'Regina', 'SK', true, NULL),
('Amanda Grand', 'other', '306-630-9052', 'fosteringliteracyyqr@gmail.com', NULL, NULL, 'Regina', 'SK', true, NULL),
('Brianne Grane', 'occupational_therapy', '306-757-9959', 'info@pathwayslearning.ca', 'https://www.pathwayslearning.ca', NULL, 'Regina', 'SK', true, NULL),
('Bryanna Graves', 'psychology', '306-262-2229', 'b.graves@qbpsychology.ca', 'https://www.qbpsychology.ca/graves', NULL, 'Saskatoon', 'SK', true, NULL),
('Kathy Griffiths', 'other', '306-280-0130', 'kgriffiths@sasktel.net', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Vanessa Grimstad', 'speech_language', '306-552-7771', 'Tania.Thomas@speechlanguagebuilders.com', 'https://speechlanguagebuilders.com', NULL, 'Regina', 'SK', true, NULL),
('Lyndsey Grotheim', 'psychology', '306-361-4443', 'admin@elevatecounselling.net', 'https://www.elevatecounselling.net', NULL, 'Saskatoon', 'SK', true, NULL),
('Lindsay Ground', 'speech_language', '306-365-7433', 'lindsay.speechlanguage@gmail.com', NULL, NULL, 'Drake', 'SK', true, NULL),
('Emily Gushulak', 'physical_therapy', '306-291-9576', 'hello@developt.ca', 'https://www.developt.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Rikki Gusway-Kelln', 'psychology', NULL, 'rikki@wildflowerstherapy.ca', 'https://wildflowerstherapy.ca', NULL, 'Regina', 'SK', true, NULL),
('Kirsten Gutenberg', 'speech_language', '306-668-6333', 'admin@associatedspeechconsultants.ca', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Sherri Habermehl', 'other', '306-291-2605', 'habermehl.reading@gmail.com', 'https://www.habermehlreading.com', NULL, '', 'SK', true, NULL),
('Danielle Hackel', 'other', '306-757-9959', 'info@pathwayslearning.ca', 'https://www.pathwayslearning.ca', NULL, 'Regina', 'SK', true, NULL),
('Ashley Hales', 'occupational_therapy', '306-529-6637', 'admin@brighthorizonsot.ca', 'https://brighthorizonsot.ca', NULL, 'Regina', 'SK', true, NULL),
('Julia Halford', 'occupational_therapy', '306-292-7039', 'playfulheartsot@gmail.com', 'https://www.playfulheartsot.ca', NULL, 'Warman', 'SK', true, NULL),
('Anastasia Halipchak', 'speech_language', '306-552-7771', 'Tania.Thomas@speechlanguagebuilders.com', 'https://speechlanguagebuilders.com', NULL, 'Regina', 'SK', true, NULL),
('Frances Hammel-Kampus', 'psychology', '306-313-5686', 'admin@moosejawpsychology.ca', 'https://www.moosejawpsychology.ca', NULL, 'Moose Jaw', 'SK', true, NULL),
('Joni Harbin', 'occupational_therapy', '780-870-7227', 'joni.ot@huntpsychologicalservices.com', 'https://www.huntpsychologicalservices.com', NULL, 'Lloydminster', 'SK', true, NULL),
('Charlotte Harding', 'other', '306-581-9530', 'misssully3@gmail.com', NULL, NULL, 'Regina', 'SK', true, NULL),
('Elayne Harris Lorenz', 'psychology', '780-870-7227', 'jentlorenz@shaw.ca', 'https://www.huntpsychologicalservices.com', NULL, 'Lloydminster', 'SK', true, NULL),
('Daisy Hart', 'other', '306-231-7226', 'hartd.tutor@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Janalyn Hastings', 'other', '905-801-5489', 'janalyn.hastings@gmail.com', NULL, NULL, 'Shaunavon', 'SK', true, NULL),
('Dr. Deb Hay', 'psychology', '306-249-4472', 'drdhay@sasktel.net', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Karin Heaney', 'occupational_therapy', '306-220-4616', 'littlemomentsot@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Nicole Hebert', 'psychology', '306-694-2222', 'nicole.hebert@moosejawmfrc.ca', 'https://cfmws.ca/support-services/families/military-family-resource-centres', NULL, 'Moose Jaw', 'SK', true, NULL),
('Ian Hecht', 'other', '306-651-2223', 'saskatoon@oxfordlearning.com', 'https://oxfordlearning.com/locations/saskatoon-tutoring', NULL, 'Saskatoon', 'SK', true, NULL),
('Crystal Heck', 'speech_language', '780-870-7227', 'speechtherapy@huntpsychologicalservices.com', 'https://www.huntpsychologicalservices.com', NULL, 'Lloydminster', 'SK', true, NULL),
('Malissa (Missy) Helfrick', 'other', '306-581-3908', 'rootedcrownwellness@gmail.com', 'https://www.facebook.com/rootedcrownwellness', NULL, 'Regina', 'SK', true, NULL),
('D''Arcy Helmer', 'psychology', '306-244-2353', 'drhelmer@innergycomprehensive.com', 'https://innergycomprehensive.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Jessi Henderson', 'speech_language', '306-461-4634', 'jessihenderson.slp@gmail.com', 'https://alaralearning.com', NULL, 'Estevan', 'SK', true, NULL),
('Meghan Herom', 'speech_language', '306-347-7284', 'info@pathwayslearning.ca', 'https://www.pathwayslearning.ca', NULL, 'Regina', 'SK', true, NULL),
('Shannon Hill', 'aba_ibi', '306-270-2852', 'shannonhill1966@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Cinthia Hill-Bird', 'speech_language', '306-716-6248', 'cinthiamhill@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Sumita Hintz', 'physical_therapy', '306-700-0120', 's.hintz@prairieviewphysiotherapy.ca', 'https://www.prairieviewphysiotherapy.ca', NULL, 'Yorkton', 'SK', true, NULL),
('Jacqueline Hobbs', 'speech_language', '306-373-1272', 'cjhobbs@sasktel.net', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Holli Homes', 'occupational_therapy', '306-529-6637', 'admin@brighthorizonsot.ca', 'https://brighthorizonsot.ca', NULL, 'Regina', 'SK', true, NULL),
('Coleen Honra', 'occupational_therapy', '306-668-0066', 'coleen@theraplaypeds.com', 'https://www.theraplaypeds.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Desiree Hortness', 'other', '306-270-7205', 'desiree@toucanlearning.ca', 'https://toucanlearning.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Eden Huber', 'speech_language', NULL, 'info@pathwayslearning.ca', 'https://www.pathwayslearning.ca', NULL, 'Regina', 'SK', true, NULL),
('Katia Hucl', 'other', '306-241-0347', 'novanutritionsk@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Judith Hunchak', 'other', '306-651-0771', 'smurfostarryeyed@yahoo.ca', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Christy Hunt', 'psychology', '780-870-7227', 'info@huntpsychologicalservices.com', 'https://www.huntpsychologicalservices.com', NULL, 'Lloydminster', 'SK', true, NULL),
('Mackenzi Hus', 'speech_language', '306-281-5289', 'mackenzi.hus@gmail.com', 'https://www.chitchatspeechtherapysk.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Juliane Hydamaka', 'psychology', '306-716-7995', 'julianeddc@gmail.com', 'https://www.deeplyconnected.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Kayla Ingram', 'other', '306-381-6161', 'misskaylasstarstudents@gmail.com', 'https://misskaylasstarstudents.weebly.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Nimra Iqbal', 'aba_ibi', '306-570-4273', 'info@abacs.ca', 'https://www.abacs.ca', NULL, 'Regina', 'SK', true, NULL),
('MacKenzie Isaak', 'speech_language', NULL, 'covetherapies@gmail.com', 'https://covetherapies.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Amber Istace', 'speech_language', '306-861-7793', 'istaceamber@gmail.com', NULL, NULL, 'Weyburn', 'SK', true, NULL),
('Crystal Itterman', 'occupational_therapy', '306-281-9933', 'crystalitterman@yahoo.ca', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Arlene Jachak', 'occupational_therapy', '306-519-3450', 'sensational.livingot1@gmail.com', NULL, NULL, 'Regina', 'SK', true, NULL),
('Anne-Marie Jakeway', 'speech_language', '306-420-0860', 'annemarie@borealvoicestherapy.com', 'https://borealvoicestherapy.com', NULL, 'Prince Albert', 'SK', true, NULL),
('Jayden (Jung-min) Jang', 'aba_ibi', '639-994-7144', 'jayden.jang@saskautismcenter.com', 'https://saskautismcenter.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Sarah Janz', 'psychology', '306-565-6000', 'admin@twinflamecounselling.com', 'https://twinflamecounselling.com', NULL, 'Regina', 'SK', true, NULL),
('Janelle Janzen', 'psychology', '306-581-6110', 'janelle@wildflowerschild.com', 'https://wildflowerstherapy.ca', NULL, 'Regina', 'SK', true, NULL),
('Heather Jeancart', 'psychology', '306-940-8998', 'psych.services@evergreensask.com', NULL, NULL, 'Prince Albert', 'SK', true, NULL),
('April Johnson', 'occupational_therapy', '306-717-6213', 'apriljohnsontherapy@outlook.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Alexandra Jordan', 'psychology', '306-920-8881', 'admin@prairiehopewellenss.com', 'https://www.prairiehopewellness.net', NULL, 'Warman', 'SK', true, NULL),
('Kim Jungman', 'other', '306-222-1165', 'pureharmonyequine@gmail.com', 'https://www.pureharmonyequine.com', NULL, 'Duck', 'SK', true, NULL),
('Carter Junk', 'aba_ibi', NULL, 'info@saskbc.com', 'https://www.saskbehaviourconsulting.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Jessica Kaastrup', 'other', '780-870-7227', 'jessica@huntpsychologicalservices.com', NULL, NULL, 'Lloydminster', 'SK', true, NULL),
('Arti Kaushal', 'psychology', '306-801-1119', 'info@arcadiancounselling.ca', 'https://arcadiancounselling.ca', NULL, 'Regina', 'SK', true, NULL),
('Dawn Kellington', 'psychology', '306-717-7272', 'dawn.createcc@gmail.com', 'https://kellingtoncounselling.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Julia Kelly', 'other', '306-382-2039', 'juliakellyrd@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Chantal Kesslering', 'speech_language', '306-368-7224', 'chantal.kesslering@gmail.com', NULL, NULL, 'Regina', 'SK', true, NULL),
('Tiffany Keyworth', 'speech_language', '306-262-6505', 'tiffany.keyworth@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Lindsay Kiefer', 'other', '306-227-7188', 'lmkiefer2001@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Jasmine Kindred', 'psychology', '306-551-1462', 'kindredsoulconnection@gmail.com', NULL, NULL, 'Regina', 'SK', true, NULL),
('Delaney King', 'other', '306-212-0454', 'delaney@sweetgrassassessments.com', 'https://sweetgrassassessments.com', NULL, 'Prince Albert', 'SK', true, NULL),
('Meghan Kirkpatrick', 'psychology', '306-546-5674', 'meghan@joshuatreelearning.com', 'https://joshuatreelearning.com', NULL, 'Regina', 'SK', true, NULL),
('Allison Kist', 'speech_language', '306-843-7624', 'info@chitchatspeechtherapysk.com', 'https://www.chitchatspeechtherapysk.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Cory Klassen', 'speech_language', '306-491-9355', 'cory@speechtherapysaskatoon.com', 'https://speechtherapysaskatoon.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Cassandra Knisely', 'physical_therapy', '306-384-7080', 'cassandra@kidsphysio.ca', 'https://www.kidsphysio.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Fred Kohuch', 'other', '306-539-8187', 'prairies@tutorbright.com', 'https://www.tutorbright.com/tutoring-regina', NULL, 'Regina', 'SK', true, NULL),
('Kaitlin Kolbe', 'speech_language', '306-853-7624', 'info@chitchatspeechtherapysk.com', 'https://www.chitchatspeechtherapysk.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Julia Koop', 'physical_therapy', '306-373-0060', 'julia@holisticphysiowellness.ca', 'https://www.holisticphysiowellness.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Allison Kotrla', 'speech_language', '306-596-2107', 'akotrla@sasktel.net', NULL, NULL, 'Regina', 'SK', true, NULL),
('Angela Kretschmer', 'occupational_therapy', '306-757-9959', 'admin@outcomestherapy.com', 'https://www.pathwayslearning.ca', NULL, 'Regina', 'SK', true, NULL),
('Kelsey Krieger', 'other', '306-461-4388', 'kelsey.krieger@hotmail.com', NULL, NULL, 'Weyburn', 'SK', true, NULL),
('Wendy Kritzer', 'psychology', '306-260-4178', 'thecounsellingcorner@sasktel.net', 'https://www.thecounsellingcorner.ca', NULL, 'Martensville', 'SK', true, NULL),
('Rachel Krug', 'other', '306-551-3600', 'prairiesmatchteam@tutorbright.com', 'https://www.tutorbright.com', NULL, 'Regina', 'SK', true, NULL),
('Jasmine Kuchenbrand', 'occupational_therapy', '780-872-3727', 'info@healthologyconsulting.ca', 'https://healthologyconsulting.ca', NULL, 'Lloydminster', 'SK', true, NULL),
('Emily Lalonde', 'psychology', '306-910-7511', 'e.lalonde@elementspsychology.ca', 'https://elementspsychology.ca', NULL, 'Regina', 'SK', true, NULL),
('Pamela Lamon', 'speech_language', '639-590-4312', 'connectspeechtherapy@outlook.com', 'https://www.connectspeechtherapy.com', NULL, 'Regina', 'SK', true, NULL),
('Rachelle Lamontagne', 'other', NULL, NULL, NULL, NULL, '', 'SK', true, NULL),
('Regina', 'other', '306-271-0422', 'prairiesmatchteam@tutorbright.com', NULL, NULL, 'Regina', 'SK', true, NULL),
('Carey Lamoureaux', 'speech_language', '306-575-7618', 'speechtherapyforkids@gmail.com', 'https://treehousespeechtherapy.weebly.com', NULL, 'Arcola', 'SK', true, NULL),
('Camille Lang', 'speech_language', '306-668-6333', 'camillelang.asc@gmail.com', 'https://associatedspeechconsultants.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Mike Lang', 'psychology', '306-920-8881', 'mlang@prairiehopewellness.com', 'https://www.prairiehopewellness.net', NULL, 'Melfort', 'SK', true, NULL),
('Magda Langton', 'physical_therapy', '306-384-7080', 'magda@kidsphysio.ca', 'https://www.kidsphysio.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Haylie Lashta', 'physical_therapy', '306-373-9355', 'info@warmanphysio.com', 'https://warmanphysio.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Melissa Latos', 'occupational_therapy', '306-668-0066', 'melissa@theraplaypeds.com', 'https://www.theraplaypeds.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Sandy Laturnas', 'speech_language', '306-552-7771', 'tania.thomas@speechlanguagebuilders.com', 'https://speechlanguagebuilders.com', NULL, 'Regina', 'SK', true, NULL),
('Kristen Lauen', 'other', '306-808-0233', 'prairies@tutorbright.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Madison Leier', 'speech_language', '306-249-4437', 'maddi@spectrumyxe.com', 'https://www.spectrumyxe.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Amanda Lennox', 'speech_language', '306-491-9355', 'amanda@speechtherapysaskatoon.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Warren Leonard', 'psychology', '306-620-8384', 'contact@halcyonpsychology.ca', 'https://halcyonpsychology.ca', NULL, 'Yorkton', 'SK', true, NULL),
('Miranda Lessmeister', 'speech_language', '306-231-6719', 'mirandahumboldtspeech@gmail.com', 'https://www.humboldtspeechlanguage.com', NULL, 'Humboldt', 'SK', true, NULL),
('Josee Levasseur', 'speech_language', '306-565-2366', 'josee.levasseur@live.ca', NULL, NULL, 'Regina', 'SK', true, NULL),
('Erin Levnaich', 'speech_language', '306-380-7252', 'hello@skpediatrictherapies.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Shay-Lea Lewis', 'occupational_therapy', '306-690-4241', 'admin@ccot.ca', 'https://carachowot.therabyte.app/site', NULL, 'Moose Jaw', 'SK', true, NULL),
('Jessica Liao', 'speech_language', '306-850-8442', 'jessica@associatedspeechconsultants.ca', 'http://www.associatedspeechconsultants.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Seth Lipton', 'other', '306-220-1691', 'hello@roadwaysliteracy.com', 'https://www.roadwaysliteracy.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Madison Long', 'speech_language', '780-870-7227', 'info@huntpsychologicalservices.com', 'https://www.huntpsychologicalservices.com', NULL, 'Lloydminster', 'SK', true, NULL),
('Monique Lozinsky', 'occupational_therapy', NULL, 'hello@developt.ca', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Victoria Luke', 'other', '306-978-7323', 'sylvan.saskatoon@sylvanlearningsaskatoon.ca', 'https://www.sylvanlearning.com/locations/ca/sk/saskatoon-tutoring/saskatoon', NULL, 'Saskatoon', 'SK', true, NULL),
('Debbie MacDonald', 'psychology', '306-630-4214', 'debbiemacdonald02@gmail.com', 'https://aspire-wellness.ca', NULL, 'Regina', 'SK', true, NULL),
('Debrah MacDonald', 'occupational_therapy', '306-381-5237', 'deb@otkindredcare.com', 'https://www.thevillageyxe.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Jilleun MacDonald', 'speech_language', '306-581-2652', 'jilleunmac@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Kendra MacDonald', 'occupational_therapy', '306-668-0066', 'kendra@theraplaypeds.com', 'https://www.theraplaypeds.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Cody MacSorely', 'psychology', NULL, 'hello@wildflowerstherapy.ca', 'https://wildflowerstherapy.ca', NULL, 'Regina', 'SK', true, NULL),
('Kennedy Magotiaux', 'occupational_therapy', '306-840-7596', 'kennedymagotiaux.ot@gmail.com', NULL, NULL, 'Moosomin', 'SK', true, NULL),
('Kasey Mahnic', 'psychology', '306-757-9959', 'info@pathwayslearning.ca', NULL, NULL, 'Regina', 'SK', true, NULL),
('Megan Mainville', 'occupational_therapy', '780-872-4127', 'meganmariemainville@gmail.com', NULL, NULL, 'Lloydminster', 'SK', true, NULL),
('Emma Majcher', 'speech_language', '306-668-0066', 'admin@associatedspeechconsultants.ca', 'https://www.associatedspeechconsultants.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Janae Malcolm', 'speech_language', '306-552-7771', 'tania.thomas@speechlanguagebuilders.com', 'https://speechlanguagebuilders.com', NULL, 'Regina', 'SK', true, NULL),
('Rachel Mamer', 'physical_therapy', '306-384-7080', 'rachel@kidsphysio.ca', 'https://www.kidsphysio.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Laura Man', 'psychology', '306-502-3836', 'lauraman@joshuatreelearning.com', 'https://joshuatreelearning.com', NULL, 'Regina', 'SK', true, NULL),
('Kennedy Manning', 'speech_language', '780-870-7227', 'kennedy.slp@huntpsychologicalservices.com', 'https://www.huntpsychologicalservices.com', NULL, 'Lloydminster', 'SK', true, NULL),
('Naomi Manske', 'speech_language', '306-249-4437', 'naomi@spectrumyxe.com', 'https://www.spectrumyxe.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Jennifer Markosky', 'speech_language', '306-491-9355', 'jenn@speechtherapysaskatoon.com', 'https://speechtherapysaskatoon.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Orlene Martens', 'speech_language', '306-955-4739', 'omartens@shaw.ca', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Maegan Mason', 'speech_language', '306-757-9959', 'info@pathwayslearning.ca', 'https://www.pathwayslearning.ca', NULL, 'Regina', 'SK', true, NULL),
('Nancy Masuda', 'psychology', '306-461-6383', 'nancy@wildflowerschild.com', 'https://wildflowerstherapy.ca', NULL, 'Regina', 'SK', true, NULL),
('Alysha Maxin', 'aba_ibi', NULL, 'info@saskbc.com', 'https://www.saskbehaviourconsulting.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Jennifer Mayson', 'aba_ibi', NULL, 'info@saskbc.com', 'https://www.saskbehaviourconsulting.com/home-based-aba-therapy', NULL, 'Saskatoon', 'SK', true, NULL),
('Riegann McAuley', 'other', '306-717-6291', 'riegann@foodtofit.ca', 'https://foodtofit.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Michelle McBride', 'other', '306-749-7434', 'elryacademics@gmail.com', 'https://www.elryacademics.com', NULL, 'Prince Albert', 'SK', true, NULL),
('Chelsea McConnell', 'psychology', '306-240-8693', 'mcconnellpsych@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Erin McCormick', 'other', '306-270-1782', 'erin.mccormick@msn.com', 'https://www.equilibriumtr.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Cailey McCulloch', 'other', '306-715-0077', 'nextstepsyxe@gmail.com', 'https://www.thevillageyxe.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Terryann McCurry', 'speech_language', '306-552-7771', 'Tania.Thomas@speechlanguagebuilders.com', 'https://speechlanguagebuilders.com', NULL, 'Regina', 'SK', true, NULL),
('Kaitlin McKenzie', 'other', '780-870-7227', 'kaitlin@huntpsychologicalservices.com', 'https://www.huntpsychologicalservices.com', NULL, 'Lloydminster', 'SK', true, NULL),
('Heather McKnight', 'physical_therapy', NULL, 'hello@developt.ca', 'https://www.developt.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Jennifer McLean', 'other', '306-960-7307', 'jennifermclean242@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Rachel McLean', 'speech_language', '306-668-6333', 'admin@associatedspeechconsultants.ca', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Megan Mee', 'other', '306-808-0233', 'prairies@tutorbright.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Alyson Melnyk', 'occupational_therapy', '306-380-7252', 'hello@skpediatrictherapies.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Sarah Mikael', 'psychology', '306-881-2220', 'sarahmikael2020@gmail.com', 'https://thrive-counselling.online', NULL, 'Saskatoon', 'SK', true, NULL),
('Lee Millar', 'speech_language', '306-450-5994', 'millar91@myaccess.ca', NULL, NULL, 'Regina', 'SK', true, NULL),
('Haley Miller', 'other', '306-209-9691', 'haley@pathwayslearning.ca', 'https://www.pathwayslearning.ca', NULL, 'Regina', 'SK', true, NULL),
('Kaylee Miller', 'aba_ibi', '306-740-2002', 'kaylee@insightfulgrowthpathways.org', NULL, NULL, 'Langenburg', 'SK', true, NULL),
('Lexi Milligan', 'other', '306-757-7323', 'leximmilligan@hotmail.com', 'https://www.sylvanlearning.com', NULL, 'Regina', 'SK', true, NULL),
('Erin Minogue', 'physical_therapy', '306-291-0912', 'erin@minoguephysiotherapy.ca', 'https://erinminoguept.janeapp.com', NULL, 'Elrose', 'SK', true, NULL),
('Taryn Moe', 'speech_language', '306-747-8295', 'tarynmoe@gmail.com', 'https://itsaspeechthing.com', NULL, 'Prince Albert', 'SK', true, NULL),
('Jillian Morgan', 'speech_language', '306-280-3396', 'info@customspeechtherapy.ca', 'https://customspeechtherapy.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Kereen Morrison-Spence', 'other', '639-317-7704', 'kereenmorrison@yahoo.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Erin Moss', 'psychology', '306-920-8881', 'emoss@prairiehopewellness.com', 'https://www.prairiehopewellness.net', NULL, 'Melfort', 'SK', true, NULL),
('Nausha Muc', 'speech_language', '306-371-2636', 'nausha@speechtherapysaskatoon.com', 'https://speechtherapysaskatoon.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Florence Mudzongo', 'psychology', '306-717-9917', 'Savanna.C.S@outlook.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Lori Mulholland', 'occupational_therapy', NULL, 'mulhollandloriot@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Lindsay Munroe', 'other', '306-933-3222', 'hello@thesln.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Hannah Murray', 'other', '306-290-2110', 'hannah@vitalitynutrition.ca', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Betty Musfin', 'physical_therapy', '306-384-7080', 'betty@kidsphysio.ca', 'https://www.kidsphysio.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Carissa Myers', 'psychology', '306-533-2984', 'carissamyers@dragonflycfwc.ca', 'https://dragonflycfwc.ca', NULL, 'Regina', 'SK', true, NULL),
('Carla Mysko', 'other', '306-651-2223', 'saskatoon@oxfordlearning.com', 'https://oxfordlearning.com/locations/saskatoon-tutoring', NULL, 'Saskatoon', 'SK', true, NULL),
('Jenna Nazarali', 'physical_therapy', '306-384-7080', 'Jenna@kidsphysio.ca', 'https://www.kidsphysio.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Linda Nelson', 'other', '306-441-0514', 'lnelson@sasktel.net', NULL, NULL, 'Battleford', 'SK', true, NULL),
('Kendra Nesbitt', 'psychology', '306-276-7253', 'kendra.nesbitt@heartlandpsychology.ca', 'https://www.heartlandpsychology.ca', NULL, 'Nipawin', 'SK', true, NULL),
('Brendan Newton', 'psychology', '306-370-0510', 'brendan@stridestherapies.ca', 'https://www.stridestherapies.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Beth Ng', 'speech_language', '306-290-5506', 'bethngslp@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Y Thi Nhu (Julie) Nguyen', 'other', '639-999-9559', 'julie.nguyen1619@gmail.com', NULL, NULL, '', 'SK', true, NULL),
('Kalee Nolan', 'speech_language', '306-434-0033', 'info@prairieskyspeech.com', 'https://prairieskyspeech.com', NULL, 'Moosomin', 'SK', true, NULL),
('Kristy Novak Leverick', 'other', '306-220-3038', 'hello@roadwaysliteracy.com', 'https://www.roadwaysliteracy.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Meghan Nowosad', 'occupational_therapy', '780-404-5279', 'meghan@mandmoccupationaltherapy.com', 'https://mandmoccupationaltherapy.com', NULL, '', 'SK', true, NULL),
('Rileigh Nurse', 'other', '306-209-7623', 'rileigh.nurse@gmail.com', NULL, NULL, 'Regina', 'SK', true, NULL),
('Karli Ochitwa', 'other', NULL, 'nextbitenutrition@gmail.com', 'https://nextbitenutrition.janeapp.com', NULL, '', 'SK', true, NULL),
('Deena Offet', 'speech_language', '306-435-9719', 'deena.offet@me.com', NULL, NULL, 'Moosomin', 'SK', true, NULL),
('Emma Orr', 'other', '306-262-4129', 'emma.orr@outlook.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Jenn Osberg', 'psychology', '306-630-6184', NULL, NULL, NULL, 'Moose Jaw', 'SK', true, NULL),
('Briana Panchyshyn', 'psychology', '306-920-8881', 'bpanchyshyn@prairiehopewellness.com', 'https://www.prairiehopewellness.net', NULL, 'Nipawin', 'SK', true, NULL),
('Shelby Pardy', 'speech_language', '306-757-9959', 'info@pathwayslearning.ca', 'https://www.pathwayslearning.ca', NULL, 'Regina', 'SK', true, NULL),
('Karen Jinhyung Park', 'aba_ibi', '639-916-1934', 'park.karen.j@gmail.com', 'https://saskautismcenter.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Judy Parley', 'psychology', '855-581-2341', 'info@stablesolutions.website', 'https://www.stablesolutions.website', NULL, 'Southey', 'SK', true, NULL),
('Shamima Parvin', 'aba_ibi', '306-880-5044', 'shamimwork@yahoo.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Kathryn Pashovitz', 'speech_language', '306-922-1200', 'branchingout@sasktel.net', NULL, NULL, 'Prince Albert', 'SK', true, NULL),
('Chantelle Payot', 'other', '306-501-2630', 'cats_meow2012@hotmail.com', NULL, NULL, 'Regina', 'SK', true, NULL),
('Rachel Pelachaty', 'occupational_therapy', '866-923-5664', 'rachel@carterscounselling.ca', 'https://carterscounsellingservices.ca', NULL, 'Martensville', 'SK', true, NULL),
('Orenda Pelzer', 'speech_language', '306-550-2678', 'orenda@reginaspeechcentre.com', NULL, NULL, 'Regina', 'SK', true, NULL),
('Jamie Perkins', 'speech_language', '306-552-7771', 'jamie.perkins@speechandlanguagebuilders.com', 'https://speechlanguagebuilders.com', NULL, 'Regina', 'SK', true, NULL),
('Tessia Philipenko', 'speech_language', '306-491-9355', 'tessia@speechtherapysaskatoon.com', 'https://speechtherapysaskatoon.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Courtney Pickard', 'other', '306-380-4139', 'pickardliteracy@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Tammy Plews', 'psychology', '306-621-2518', 'tammy@shearerwcs.com', NULL, NULL, 'Yorkton', 'SK', true, NULL),
('Tiffany Powell', 'occupational_therapy', '306-398-5530', 'hello@thoosatherapy.com', 'https://www.thoosatherapy.com', NULL, 'Southwest', 'SK', true, NULL),
('Lana Prescott', 'speech_language', '306-668-0066', 'admin@associatedspeechconsultants.com', 'https://www.associatedspeechconsultants.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Kelsey Prevost', 'psychology', '306-371-0391', 'connect@thevillageyxe.ca', 'https://www.thevillageyxe.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Kahra Price', 'other', '306-441-2852', 'kahra.price@gmail.com', NULL, NULL, 'North Battleford', 'SK', true, NULL),
('Robyn Price', 'other', '306-717-6291', 'robyn@foodtofit.ca', 'https://foodtofit.ca', NULL, 'Regina', 'SK', true, NULL),
('Julia Pringle', 'speech_language', '306-539-4929', 'info@pathwayslearning.ca', 'https://www.pathwayslearning.ca', NULL, 'Regina', 'SK', true, NULL),
('Nathan Prokopchuk', 'other', '306-420-0144', 'natejamesp@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Christa Pryce', 'speech_language', '306-577-8432', 'christa.pryce@hotmail.com', NULL, NULL, 'Wawota', 'SK', true, NULL),
('Kaylee Pylypow', 'occupational_therapy', '780-870-7227', 'kaylee.ot@huntpsychologicalservices.com', 'https://www.huntpsychologicalservices.com', NULL, 'Lloydminster', 'SK', true, NULL),
('Kristen Quigley', 'physical_therapy', '306-291-9576', 'hello@developt.ca', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Dawn Rain', 'psychology', '306-260-1297', 'dawn.rain@hotmail.com', 'https://family-counselling.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Ian Reid', 'psychology', '306-781-1817', 'ian.reid@ranchehrlo.ca', 'https://ehrlo.com/counselling/our-services/counselling', NULL, 'Regina', 'SK', true, NULL),
('Maggie Reid', 'speech_language', '306-933-3222', 'hello@thesln.com', 'https://www.thesln.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Wannetta Reimer', 'psychology', '866-923-5664', 'wannetta@carterscounselling.ca', 'https://carterscounsellingservices.ca', NULL, 'Martensville', 'SK', true, NULL),
('Aimee Resch', 'speech_language', NULL, 'aimeeslp19@gmail.com', NULL, NULL, 'Leader', 'SK', true, NULL),
('Wanda Reynaud', 'psychology', '306-280-3396', 'dogzrock190@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Jasmin Richter', 'occupational_therapy', '306-360-7379', 'wildheartOT@gmail.com', NULL, NULL, 'Humboldt', 'SK', true, NULL),
('Sheryl Riis', 'other', '306-978-7323', 'sylvansk.ed@shaw.ca', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Kiara Riou', 'other', '306-250-6949', 'kiara.riou@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Megan Roelfsema', 'speech_language', '306-861-6803', 'megan.roelfsema@gmail.com', 'https://www.facebook.com/smoothsailingspeech', NULL, 'Weyburn', 'SK', true, NULL),
('Dyan Roth', 'occupational_therapy', '306-757-9959', 'info@pathwayslearning.ca', 'https://www.pathwayslearning.ca', NULL, 'Regina', 'SK', true, NULL),
('Shantelle Roundell', 'other', '306-501-4160', 'shantelleroundell@gmail.com', 'https://www.yqrtutors.com', NULL, 'Regina', 'SK', true, NULL),
('Lindsay Roysum', 'occupational_therapy', '306-543-0990', 'lroysum@staplefordhealth.ca', 'https://www.staplefordhealth.ca', NULL, 'Regina', 'SK', true, NULL),
('Brenda Roznowski', 'occupational_therapy', '639-822-7177', 'brendaroznowski@gmail.com', NULL, NULL, 'Lloydminster', 'SK', true, NULL),
('Brittney Rude', 'speech_language', '306-491-9355', 'brittney@speechtherapysaskatoon.com', 'https://speechtherapysaskatoon.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Kendall Sather', 'other', '306-231-4720', 'reginareadinessacademy@gmail.com', 'https://www.yqrtutors.com', NULL, 'Regina', 'SK', true, NULL),
('Bonny Savage', 'other', '306-790-2000', 'regina@oxfordlearning.com', 'https://oxfordlearning.com', NULL, '', 'SK', true, NULL),
('Cristin Sawchuk', 'other', '306-871-5288', 'cristin.sawchuk@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Tara Schauenberg', 'speech_language', '306-630-3871', 'schauenbergtara@gmail.com', NULL, NULL, 'Moose Jaw', 'SK', true, NULL),
('Alyssa Schienbein', 'aba_ibi', '306-306-1517', 'exceptionallyeducated@gmail.com', 'https://exceptionallyeducated.ca', NULL, 'Lloydminster', 'SK', true, NULL),
('Joel Schindelka', 'other', '306-535-2855', 'joelschindelka@gmail.com', NULL, NULL, 'Regina', 'SK', true, NULL),
('Katie Schlosser', 'speech_language', '306-281-3967', 'gateway.sll.sk@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Amy Schmitt', 'speech_language', '780-619-0596', 'hello@babbleandbloom.ca', 'https://www.babbleandbloom.ca', NULL, 'Lloydminster', 'SK', true, NULL),
('Ashley Schramm', 'occupational_therapy', '306-668-0066', 'ashley@theraplaypeds.com', 'https://www.theraplaypeds.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Mackenzie Schulz', 'occupational_therapy', '306-757-9959', 'info@pathwayslearning.ca', 'https://www.pathwayslearning.ca', NULL, 'Regina', 'SK', true, NULL),
('Deanna Schwindt', 'psychology', '306-546-5674', 'deanna@joshuatreelearning.com', 'https://joshuatreelearning.com', NULL, 'Weyburn', 'SK', true, NULL),
('Amy Scott-Wawro', 'speech_language', '306-465-7667', 'amy.scottwawro@gmail.com', NULL, NULL, 'Regina', 'SK', true, NULL),
('Lauren Seabrook', 'occupational_therapy', '306-280-8565', 'lauren@milestonesot.ca', 'https://milestonesot.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Betty Setka', 'other', '306-862-1414', 'jsetka@sasktel.net', NULL, NULL, 'Warman', 'SK', true, NULL),
('Kirsten Seto', 'speech_language', '403-923-6483', 'kirsten.seto@itsaspeeching.com', 'https://itsaspeechthing.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Meaghan Shewchuk', 'physical_therapy', '888-611-2854', 'meaghan.shewchuk@lifemark.ca', 'https://www.lifemark.ca/brand/alta-sask-wellness', NULL, 'Lloydminster', 'SK', true, NULL),
('Jessica Shirley', 'other', NULL, NULL, NULL, NULL, '', 'SK', true, NULL),
('Saskatoon', 'other', '514-291-5213', 'jmarieshirley@outlook.com', 'https://www.tutorbright.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Erin Sifert', 'speech_language', '306-591-0490', 'info@pathwayslearning.ca', 'https://www.pathwayslearning.ca', NULL, 'Regina', 'SK', true, NULL),
('Jennifer Simonson', 'occupational_therapy', '306-217-7530', 'simonsontherapy@outlook.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Christopher Singleton', 'psychology', '306-380-8801', 'drsingleton@prairiechilddevelopment.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Arysha Skalicky', 'psychology', '306-933-3222', 'hello@thesln.com', 'https://thesln.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Meagan Smith', 'occupational_therapy', '306-933-2222', 'hello@thesln.com', 'https://thesln.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Stephanie Smith', 'psychology', '306-291-0804', 'stephaniesmith.yxe@gmail.com', 'https://www.thevillageyxe.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Tyra Smith', 'psychology', '306-943-4345', 'therapies@clearhealth.solutions', 'https://www.clearhealthsolutions.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Hannah Sollid', 'occupational_therapy', '306-668-0066', 'hannah@theraplaypeds.com', 'https://www.theraplaypeds.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Dr. Lara Spagrud', 'psychology', '306-664-6647', 'reception@casa-psych.ca', 'https://casapsych.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Josie Stan', 'physical_therapy', '306-384-7080', 'josie@kidsphysio.ca', 'https://www.kidsphysio.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Karrah Stangby', 'physical_therapy', '306-690-4241', 'karramstangby@gmail.com', 'https://carachowot.therabyte.app/site', NULL, 'Moose Jaw', 'SK', true, NULL),
('Deanna Starr', 'occupational_therapy', '306-480-0086', 'deanna@miskihnak.ca', 'https://miskihnak.ca', NULL, 'North Battleford', 'SK', true, NULL),
('Stephanie Stene', 'other', '306-222-2717', 'stenes_123@icloud.com', 'https://www.facebook.com/profile.php?id=61564086389643', NULL, 'Martensville', 'SK', true, NULL),
('Samara Stenson', 'other', '306-231-0168', 'samara_stenson@hotmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Megan Stevenson', 'occupational_therapy', '306-529-6637', 'admin@brighthorizonsot.ca', 'https://brighthorizonsot.ca', NULL, 'Regina', 'SK', true, NULL),
('Erin Sthamann', 'psychology', '306-757-9959', 'info@pathwayslearning.ca', NULL, NULL, 'Regina', 'SK', true, NULL),
('Julie Stocki', 'psychology', '306-922-1200', 'branchingout@sasktel.net', NULL, NULL, 'Prince Albert', 'SK', true, NULL),
('Renelle Stoicescu', 'speech_language', '306-668-6333', 'admin@associatedspeechconsultants.ca', 'http://www.associatedspeechconsultants.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Darby Stolz', 'speech_language', '780-870-7227', 'darby.slp@huntpsychologicalservices.com', 'https://www.huntpsychologicalservices.com', NULL, 'Lloydminster', 'SK', true, NULL),
('Erin Strueby', 'speech_language', '306-231-6642', 'humboldtspeech@gmail.com', 'https://www.humboldtspeechlanguage.com', NULL, 'Humboldt', 'SK', true, NULL),
('Leanne Sudom', 'speech_language', '306-552-7771', 'tania.thomas@speechlanguagebuilders.com', 'https://speechlanguagebuilders.com', NULL, 'Regina', 'SK', true, NULL),
('Tasha Sudsbear', 'speech_language', '306-621-5602', 'tashasudsbear@gmail.com', NULL, NULL, 'Yorkton', 'SK', true, NULL),
('Kristina Sutherland', 'psychology', '306-361-9519', 'kristina@horizonpsychology.ca', 'https://horizonpsychology.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Kristen Sylvester', 'speech_language', NULL, 'hello@wildflowerstherapy.ca', 'https://wildflowerstherapy.ca', NULL, 'Regina', 'SK', true, NULL),
('Alyson Tallman Hartmann', 'speech_language', '306-232-1088', 'agjtallman@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Donna Taylor', 'other', '306-554-8725', 'donnataylor.ca@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Maureen Tazzioli', 'other', '306-775-3787', 'maureen@inthehowse.com', 'https://inthehowse.com', NULL, 'Regina', 'SK', true, NULL),
('Shallon Terry', 'other', '306-371-9894', 'shallon@roadwaysliteracy.com', 'https://www.roadwaysliteracy.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Cheryl Thacker', 'psychology', '306-491-7014', 'cherylthacker3087@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Cari Thiele', 'speech_language', '306-757-9959', 'info@pathwayslearning.ca', NULL, NULL, 'Regina', 'SK', true, NULL),
('Tania Thomas', 'speech_language', '306-552-7771', 'tania.thomas@speechlanguagebuilders.com', 'https://speechlanguagebuilders.com', NULL, 'Regina', 'SK', true, NULL),
('Kendall Thomas-McEachern', 'psychology', '306-260-7022', 'kendall@whimsycounselling.com', 'https://www.whimsycounselling.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Maureen Thompson', 'psychology', '306-565-5576', 'Maureen@cultivatewellnessyqr.ca', 'https://cultivatewellnessyqr.ca', NULL, 'Regina', 'SK', true, NULL),
('Kathy Tiefenbach', 'other', '306-539-3191', 'kathy.tiefe@gmail.com', NULL, NULL, 'Regina', 'SK', true, NULL),
('Kelsi Toews, Ph.D.', 'psychology', '306-262-2229', 'dr.toews@qbpsychology.ca', 'https://www.qbpsychology.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Cindy Toniello', 'other', '306-533-0927', 'cindy.toniello@gmail.com', NULL, NULL, 'Regina', 'SK', true, NULL),
('Candace Tonner', 'psychology', '306-901-7511', 'info@elementspsychology.ca', 'https://elementspsychology.ca', NULL, 'Regina', 'SK', true, NULL),
('Alicia Totten', 'psychology', '250-488-9689', 'alicia@wildflowerschild.com', 'https://wildflowerstherapy.ca', NULL, 'Regina', 'SK', true, NULL),
('Kaley Trach', 'aba_ibi', NULL, 'info@saskbc.com', 'https://www.saskbehaviourconsulting.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Heather Tremblay', 'speech_language', '306-933-3222', 'heather@thesln.com', 'https://thesln.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Camilla Trottier', 'other', '306-220-1691', 'camilla@roadwaysliteracy.com', 'https://www.roadwaysliteracy.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Sherry Tucker', 'psychology', '306-382-2391', 'sherry@aspiretoo.ca', 'https://aspiretoo.ca', NULL, 'Saskatoon', 'SK', true, NULL),
('Mia (Maria) Van Dyke', 'speech_language', '306-533-9915', 'prairiebasic@sasktel.net', 'https://www.prairiebasic.ca', NULL, 'Moose Jaw', 'SK', true, NULL),
('Carissa Vance', 'speech_language', '306-757-9959', 'info@pathwayslearning.ca', 'https://www.pathwayslearning.ca', NULL, 'Regina', 'SK', true, NULL),
('Pam Vukman', 'occupational_therapy', '306-531-5775', 'info@pathwayslearning.ca', 'https://www.pathwayslearning.ca', NULL, 'Regina', 'SK', true, NULL),
('Hailey Walchuk', 'speech_language', '306-249-4437', 'hailey@spectrumyxe.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Lindsay Walker', 'occupational_therapy', '306-518-7566', 'lindsay@simplejoysot.com', 'https://www.simplejoysot.com', NULL, 'Elrose', 'SK', true, NULL),
('Deb Waring', 'occupational_therapy', '306-221-1051', 'otkids@shaw.ca', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Tina Waring', 'speech_language', '306-533-9105', 'tina@reginaspeechcentre.com', 'https://reginaspeechcentre.com', NULL, 'Regina', 'SK', true, NULL),
('Briane Webb', 'other', '306-220-1907', 'briane.webb@webbsprout.com', 'https://www.webbsprout.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Darren Weinrauch', 'other', '306-280-0894', 'prairiesmatchteam@tutorbright.com', 'https://www.tutorbright.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Elaine Weisgerber', 'psychology', '306-230-5137', 'e.weisgerber@hotmail.com', 'https://carterscounsellingservices.ca', NULL, 'Regina', 'SK', true, NULL),
('Edwina Weninger', 'other', '306-821-5019', 'j.e.weninger@telus.net', NULL, NULL, 'Dalmeny', 'SK', true, NULL),
('Nancy Whelan', 'speech_language', '780-870-7227', 'nancy.slp@huntpsychologicalservices.com', 'https://www.huntpsychologicalservices.com', NULL, 'Lloydminster', 'SK', true, NULL),
('Debi Wigelsworth', 'other', '306-321-2785', 'debi@roadwaysliteracy.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Shelby Wilkinson', 'occupational_therapy', '306-631-1495', 'expandingfuturesOT@gmail.com', NULL, NULL, 'Moose Jaw', 'SK', true, NULL),
('Kaylyn Witzaney', 'occupational_therapy', '306-668-0066', 'kaylyn@theraplaypeds.com', 'https://www.theraplaypeds.com', NULL, 'Weyburn', 'SK', true, NULL),
('Geraldine Woods', 'speech_language', '306-922-1200', 'branchingout@sasktel.net', NULL, NULL, 'Prince Albert', 'SK', true, NULL),
('Karen Wotherspoon', 'psychology', '306-546-5674', 'karen@joshuatreelearning.com', 'https://joshuatreelearning.com', NULL, 'Regina', 'SK', true, NULL),
('Shana Yates', 'occupational_therapy', '306-668-0066', 'admin@theraplaypeds.com', 'https://www.theraplaypeds.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Catherine Young', 'psychology', '306-546-5674', 'catherine@joshuatreelearning.com', 'https://joshuatreelearning.com', NULL, 'Regina', 'SK', true, NULL),
('Annelise Yung', 'other', '306-529-3521', 'a.yung@rcsd.ca', NULL, NULL, 'Regina', 'SK', true, NULL),
('Kerry Zachar', 'physical_therapy', '780-870-7227', 'kerry.pt@huntpsychologicalservices.com', 'https://www.huntpsychologicalservices.com', NULL, 'Lloydminster', 'SK', true, NULL),
('Oksana Zbitniff', 'psychology', '306-242-8993', 'admin@andersondupuis.com', 'https://www.andersondupuis.com', NULL, 'Saskatoon', 'SK', true, NULL),
('Haley Zrymiak', 'speech_language', '306-230-5523', 'haleyzrymiak@gmail.com', NULL, NULL, 'Saskatoon', 'SK', true, NULL),
('Brooke Zulak', 'speech_language', '306-560-7645', 'brooke.zulak@gmail.com', NULL, NULL, 'Estevan', 'SK', true, NULL);

-- Total providers: 457
