import type { ImageSourcePropType } from 'react-native';

export type DocumentPageAsset = {
  sourceDocument: string;
  pageNumber: number;
  width: number;
  height: number;
  image: ImageSourcePropType;
};

export const DOCUMENT_PAGE_ASSETS: DocumentPageAsset[] = [
  {
    sourceDocument: 'ADA-MMA-System-Steps.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/ADA-MMA-System-Steps-p01.jpg'),
  },
  {
    sourceDocument: 'Basement-Waterproofing-2.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/Basement-Waterproofing-2-p01.jpg'),
  },
  {
    sourceDocument: 'Basement-Waterproofing-X-Bond.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/Basement-Waterproofing-X-Bond-p01.jpg'),
  },
  {
    sourceDocument: 'Basement-Waterproofing.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/Basement-Waterproofing-p01.jpg'),
  },
  {
    sourceDocument: 'Broadcast-System-Steps.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/Broadcast-System-Steps-p01.jpg'),
  },
  {
    sourceDocument: 'Ceiling-Surface-Steps.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/Ceiling-Surface-Steps-p01.jpg'),
  },
  {
    sourceDocument: 'Color-Bond-Steps.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/Color-Bond-Steps-p01.jpg'),
  },
  {
    sourceDocument: 'Cove-Base-Detail-Plywood.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/Cove-Base-Detail-Plywood-p01.jpg'),
  },
  {
    sourceDocument: 'Cove-Base-Detail.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/Cove-Base-Detail-p01.jpg'),
  },
  {
    sourceDocument: 'Cracks-Joints-wider-14.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/Cracks-Joints-wider-14-p01.jpg'),
  },
  {
    sourceDocument: 'Drain-Detail.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/Drain-Detail-p01.jpg'),
  },
  {
    sourceDocument: 'LM-Data-Sheet.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/LM-Data-Sheet-p01.jpg'),
  },
  {
    sourceDocument: 'LM-over-concrete.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/LM-over-concrete-p01.jpg'),
  },
  {
    sourceDocument: 'LM-over-Gyp-crete.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/LM-over-Gyp-crete-p01.jpg'),
  },
  {
    sourceDocument: 'LM-Tech-Sheet.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/LM-Tech-Sheet-p01.jpg'),
  },
  {
    sourceDocument: 'Natural-Grain-Steps.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/Natural-Grain-Steps-p01.jpg'),
  },
  {
    sourceDocument: 'Natural-Shield-Data-Sheet.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/Natural-Shield-Data-Sheet-p01.jpg'),
  },
  {
    sourceDocument: 'Natural-Shield-Tech-Sheet.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/Natural-Shield-Tech-Sheet-p01.jpg'),
  },
  {
    sourceDocument: 'NuLift-Datasheet.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/NuLift-Datasheet-p01.jpg'),
  },
  {
    sourceDocument: 'Polished-Bond-Steps.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/Polished-Bond-Steps-p01.jpg'),
  },
  {
    sourceDocument: 'Pool-Deck-Resurfacing-Detail.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/Pool-Deck-Resurfacing-Detail-p01.jpg'),
  },
  {
    sourceDocument: 'Pool-Resurfacing-Detail-Interior-Below-Grade.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/Pool-Resurfacing-Detail-Interior-Below-Grade-p01.jpg'),
  },
  {
    sourceDocument: 'Power-Cleaner-Datasheet.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/Power-Cleaner-Datasheet-p01.jpg'),
  },
  {
    sourceDocument: 'PREP-E.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/PREP-E-p01.jpg'),
  },
  {
    sourceDocument: 'prestain-data-sheet.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/prestain-data-sheet-p01.jpg'),
  },
  {
    sourceDocument: 'prestain-tech-sheet.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/prestain-tech-sheet-p01.jpg'),
  },
  {
    sourceDocument: 'Satin-Stone-chemical-resistance.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/Satin-Stone-chemical-resistance-p01.jpg'),
  },
  {
    sourceDocument: 'Satin-Stone-Data-Sheet.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/Satin-Stone-Data-Sheet-p01.jpg'),
  },
  {
    sourceDocument: 'Satin-Stone-Tech-Data-Sheet.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/Satin-Stone-Tech-Data-Sheet-p01.jpg'),
  },
  {
    sourceDocument: 'Shower-Detail-Concrete.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/Shower-Detail-Concrete-p01.jpg'),
  },
  {
    sourceDocument: 'Shower-Detail-Glasroc-OSB.pdf',
    pageNumber: 1,
    width: 1024,
    height: 1280,
    image: require('../../assets/document-pages/Shower-Detail-Glasroc-OSB-p01.jpg'),
  },
  {
    sourceDocument: 'Shower-Detail-Wood.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/Shower-Detail-Wood-p01.jpg'),
  },
  {
    sourceDocument: 'Shower-Detail.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/Shower-Detail-p01.jpg'),
  },
  {
    sourceDocument: 'Shower-Drain-Detail.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/Shower-Drain-Detail-p01.jpg'),
  },
  {
    sourceDocument: 'Stair-Detail.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/Stair-Detail-p01.jpg'),
  },
  {
    sourceDocument: 'Stone-Soap-Datasheet.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/Stone-Soap-Datasheet-p01.jpg'),
  },
  {
    sourceDocument: 'Tech_Sheet_Satin-Stone-v5.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/Tech-Sheet-Satin-Stone-v5-p01.jpg'),
  },
  {
    sourceDocument: 'Tech_Sheet_TitanShield-v8.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/Tech-Sheet-TitanShield-v8-p01.jpg'),
  },
  {
    sourceDocument: 'Tech_Sheet_X-Bond-2024-v3.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/Tech-Sheet-X-Bond-2024-v3-p01.jpg'),
  },
  {
    sourceDocument: 'Titan-Gloss-Product-Sheet.pdf',
    pageNumber: 1,
    width: 1248,
    height: 1588,
    image: require('../../assets/document-pages/Titan-Gloss-Product-Sheet-p01.jpg'),
  },
  {
    sourceDocument: 'Titan-Gloss-Tech-Data-Sheet.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/Titan-Gloss-Tech-Data-Sheet-p01.jpg'),
  },
  {
    sourceDocument: 'Wall-Detail.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/Wall-Detail-p01.jpg'),
  },
  {
    sourceDocument: 'Waterproofing-Metal.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/Waterproofing-Metal-p01.jpg'),
  },
  {
    sourceDocument: 'Wood-Detail.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/Wood-Detail-p01.jpg'),
  },
  {
    sourceDocument: 'X-Bond-Over-Tile-Detail.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/X-Bond-Over-Tile-Detail-p01.jpg'),
  },
  {
    sourceDocument: 'X-BondMicrocementDataSheet2024.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/X-BondMicrocementDataSheet2024-p01.jpg'),
  },
  {
    sourceDocument: 'X-BondoverConcreteFloorDetail-2025.pdf',
    pageNumber: 1,
    width: 1224,
    height: 1584,
    image: require('../../assets/document-pages/X-BondoverConcreteFloorDetail-2025-p01.jpg'),
  },
];

export const DOCUMENT_SOURCE_URLS: Record<string, string> = {
  'ADA-MMA-System-Steps.pdf': 'https://www.semcosurfaces.com/s/ADA-MMA-System-Steps.pdf',
  'Basement-Waterproofing-2.pdf': 'https://www.semcosurfaces.com/s/Basement-Waterproofing-2.pdf',
  'Basement-Waterproofing-X-Bond.pdf': 'https://www.semcosurfaces.com/s/Basement-Waterproofing-X-Bond.pdf',
  'Basement-Waterproofing.pdf': 'https://www.semcosurfaces.com/s/Basement-Waterproofing.pdf',
  'Broadcast-System-Steps.pdf': 'https://www.semcosurfaces.com/s/Broadcast-System-Steps.pdf',
  'Ceiling-Surface-Steps.pdf': 'https://www.semcosurfaces.com/s/Ceiling-Surface-Steps.pdf',
  'Color-Bond-Steps.pdf': 'https://www.semcosurfaces.com/s/Color-Bond-Steps.pdf',
  'Cove-Base-Detail-Plywood.pdf': 'https://www.semcosurfaces.com/s/Cove-Base-Detail-Plywood.pdf',
  'Cove-Base-Detail.pdf': 'https://www.semcosurfaces.com/s/Cove-Base-Detail.pdf',
  'Cracks-Joints-wider-14.pdf': 'https://www.semcosurfaces.com/s/Cracks-Joints-wider-14.pdf',
  'Drain-Detail.pdf': 'https://www.semcosurfaces.com/s/Drain-Detail.pdf',
  'LM-Data-Sheet.pdf': 'https://www.semcosurfaces.com/s/LM-Data-Sheet.pdf',
  'LM-over-concrete.pdf': 'https://www.semcosurfaces.com/s/LM-over-concrete.pdf',
  'LM-over-Gyp-crete.pdf': 'https://www.semcosurfaces.com/s/LM-over-Gyp-crete.pdf',
  'LM-Safety-Data-Sheet.pdf': 'https://www.semcosurfaces.com/s/LM-Safety-Data-Sheet.pdf',
  'LM-Tech-Sheet.pdf': 'https://www.semcosurfaces.com/s/LM-Tech-Sheet.pdf',
  'Natural-Grain-Steps.pdf': 'https://www.semcosurfaces.com/s/Natural-Grain-Steps.pdf',
  'Natural-Shield-Data-Sheet.pdf': 'https://www.semcosurfaces.com/s/Natural-Shield-Data-Sheet.pdf',
  'Natural-Shield-SDS.pdf': 'https://www.semcosurfaces.com/s/Natural-Shield-SDS.pdf',
  'Natural-Shield-Tech-Sheet.pdf': 'https://www.semcosurfaces.com/s/Natural-Shield-Tech-Sheet.pdf',
  'NuLift-Datasheet.pdf': 'https://www.semcosurfaces.com/s/NuLift-Datasheet.pdf',
  'NuLift-SDS.pdf': 'https://www.semcosurfaces.com/s/NuLift-SDS.pdf',
  'Polished-Bond-Steps.pdf': 'https://www.semcosurfaces.com/s/Polished-Bond-Steps.pdf',
  'Pool-Deck-Resurfacing-Detail.pdf': 'https://www.semcosurfaces.com/s/Pool-Deck-Resurfacing-Detail.pdf',
  'Pool-Resurfacing-Detail-Interior-Below-Grade.pdf': 'https://www.semcosurfaces.com/s/Pool-Resurfacing-Detail-Interior-Below-Grade.pdf',
  'Power-Cleaner-Datasheet.pdf': 'https://www.semcosurfaces.com/s/Power-Cleaner-Datasheet.pdf',
  'Power-Cleaner-SDS.pdf': 'https://www.semcosurfaces.com/s/Power-Cleaner-SDS.pdf',
  'PREP-E.pdf': 'https://www.semcosurfaces.com/s/PREP-E.pdf',
  'prestain-data-sheet.pdf': 'https://www.semcosurfaces.com/s/prestain-data-sheet.pdf',
  'PreStain-SDS.pdf': 'https://www.semcosurfaces.com/s/PreStain-SDS.pdf',
  'prestain-tech-sheet.pdf': 'https://www.semcosurfaces.com/s/prestain-tech-sheet.pdf',
  'Satin-Stone-chemical-resistance.pdf': 'https://www.semcosurfaces.com/s/Satin-Stone-chemical-resistance.pdf',
  'Satin-Stone-Data-Sheet.pdf': 'https://www.semcosurfaces.com/s/Satin-Stone-Data-Sheet.pdf',
  'Satin-Stone-SDS.pdf': 'https://www.semcosurfaces.com/s/Satin-Stone-SDS.pdf',
  'Satin-Stone-Tech-Data-Sheet.pdf': 'https://www.semcosurfaces.com/s/Satin-Stone-Tech-Data-Sheet.pdf',
  'Section-09670-Fluid-Applied-Surfaces.pdf': 'https://www.semcosurfaces.com/s/Section-09670-Fluid-Applied-Surfaces.pdf',
  'Shower-Detail-Concrete.pdf': 'https://www.semcosurfaces.com/s/Shower-Detail-Concrete.pdf',
  'Shower-Detail-Wood.pdf': 'https://www.semcosurfaces.com/s/Shower-Detail-Wood.pdf',
  'Shower-Detail.pdf': 'https://www.semcosurfaces.com/s/Shower-Detail.pdf',
  'Shower-Drain-Detail.pdf': 'https://www.semcosurfaces.com/s/Shower-Drain-Detail.pdf',
  'Stair-Detail.pdf': 'https://www.semcosurfaces.com/s/Stair-Detail.pdf',
  'Stone-Soap-Datasheet.pdf': 'https://www.semcosurfaces.com/s/Stone-Soap-Datasheet.pdf',
  'Stone-Soap-SDS.pdf': 'https://www.semcosurfaces.com/s/Stone-Soap-SDS.pdf',
  'Tech_Sheet_Satin-Stone-v5.pdf': 'https://www.semcosurfaces.com/s/Tech_Sheet_Satin-Stone-v5.pdf',
  'Tech_Sheet_TitanShield-v8.pdf': 'https://www.semcosurfaces.com/s/Tech_Sheet_TitanShield-v8.pdf',
  'Tech_Sheet_X-Bond-2024-v3.pdf': 'https://www.semcosurfaces.com/s/Tech_Sheet_X-Bond-2024-v3.pdf',
  'Titan-Gloss-Product-Sheet.pdf': 'https://www.semcosurfaces.com/s/Titan-Gloss-Product-Sheet.pdf',
  'Titan-Gloss-Tech-Data-Sheet.pdf': 'https://www.semcosurfaces.com/s/Titan-Gloss-Tech-Data-Sheet.pdf',
  'Titan-Shield-SDS.pdf': 'https://www.semcosurfaces.com/s/Titan-Shield-SDS.pdf',
  'Wall-Detail.pdf': 'https://www.semcosurfaces.com/s/Wall-Detail.pdf',
  'Waterproofing-Metal.pdf': 'https://www.semcosurfaces.com/s/Waterproofing-Metal.pdf',
  'Wood-Detail.pdf': 'https://www.semcosurfaces.com/s/Wood-Detail.pdf',
  'X-Bond-Additive-SDS.pdf': 'https://www.semcosurfaces.com/s/X-Bond-Additive-SDS.pdf',
  'X-Bond-Liquid-SDS.pdf': 'https://www.semcosurfaces.com/s/X-Bond-Liquid-SDS.pdf',
  'X-Bond-Microbond-SDS.pdf': 'https://www.semcosurfaces.com/s/X-Bond-Microbond-SDS.pdf',
  'X-Bond-Over-Tile-Detail.pdf': 'https://www.semcosurfaces.com/s/X-Bond-Over-Tile-Detail.pdf',
  'X-Bond-Stone-SDS.pdf': 'https://www.semcosurfaces.com/s/X-Bond-Stone-SDS.pdf',
  'X-BondMicrocementDataSheet2024.pdf': 'https://www.semcosurfaces.com/s/X-BondMicrocementDataSheet2024.pdf',
  'X-BondoverConcreteFloorDetail-2025.pdf': 'https://www.semcosurfaces.com/s/X-BondoverConcreteFloorDetail-2025.pdf',
};

function normalizeDocumentName(value: string): string {
  return value.toLowerCase().replace(/\.pdf$/, '').replace(/[^a-z0-9]+/g, '');
}

const assetLookup = new Map(
  DOCUMENT_PAGE_ASSETS.map((asset) => [
    `${normalizeDocumentName(asset.sourceDocument)}:${asset.pageNumber}`,
    asset,
  ]),
);

const sourceUrlLookup = new Map(
  Object.entries(DOCUMENT_SOURCE_URLS).map(([sourceDocument, url]) => [
    normalizeDocumentName(sourceDocument),
    url,
  ]),
);

export function getDocumentPageAsset(sourceDocument: string, pageNumber = 1): DocumentPageAsset | undefined {
  return assetLookup.get(`${normalizeDocumentName(sourceDocument)}:${pageNumber}`);
}

export function getDocumentSourceUrl(sourceDocument: string): string | undefined {
  return sourceUrlLookup.get(normalizeDocumentName(sourceDocument));
}
