export type InstallationGuideLayer = {
  label: string;
  detail: string;
  color: string;
  textColor?: string;
};

export type InstallationGuide = {
  id: string;
  title: string;
  subtitle: string;
  category: string;
  summary: string;
  sourceDocument: string;
  sourcePage?: string;
  layers: InstallationGuideLayer[];
  steps: string[];
  materials: string[];
  askPrompt: string;
};

const xBondMaterials = ['X-Bond Liquid', 'X-Bond Stone', 'Liquid Membrane', 'Fabric', 'Sealer'];
const waterproofingMaterials = ['Liquid Membrane', 'Fabric reinforcement', 'Natural Shield', 'X-Bond system'];
const detailLayers: InstallationGuideLayer[] = [
  { label: 'Prepared substrate', detail: 'Clean, stable, approved surface', color: '#DDE7EA', textColor: '#00232D' },
  { label: 'Bond / waterproofing detail', detail: 'Primer, membrane, fabric, or system detail', color: '#9FE5E9', textColor: '#00232D' },
  { label: 'X-Bond build-up', detail: 'Scratch/base/finish as shown in the drawing', color: '#7C8A7B', textColor: '#FFFFFF' },
  { label: 'Protection', detail: 'Specified stocked Semco sealer', color: '#CF451F', textColor: '#FFFFFF' },
];

const defaultSteps = [
  'Confirm the substrate is sound, stable, clean, and dry enough for coating.',
  'Follow the layer order shown in the official drawing.',
  'Detail joints, cracks, drains, corners, transitions, and movement-risk areas before covering them.',
  'Capture the required warranty stage photos before each stage gets hidden.',
  'Ask Semco when the existing surface condition does not match the drawing.',
];

export const INSTALLATION_GUIDES: InstallationGuide[] = [
  {
    id: 'x-bond-concrete-floor-detail',
    title: 'X-Bond Concrete Floor',
    subtitle: 'Official floor build-up over concrete or panels',
    category: 'X-Bond',
    summary: 'The core X-Bond floor drawing for concrete floors and compatible concrete-board or panel substrates.',
    sourceDocument: 'X-BondoverConcreteFloorDetail-2025.pdf',
    sourcePage: 'Official floor detail',
    materials: xBondMaterials,
    askPrompt: 'Walk me through the X-Bond concrete floor detail from start to finish.',
    layers: detailLayers,
    steps: defaultSteps,
  },
  {
    id: 'x-bond-over-tile-detail',
    title: 'X-Bond Over Tile',
    subtitle: 'Tile and grout resurfacing detail',
    category: 'X-Bond',
    summary: 'Official drawing for resurfacing properly prepared tile and grout with the X-Bond system.',
    sourceDocument: 'X-Bond-Over-Tile-Detail.pdf',
    sourcePage: 'Official tile detail',
    materials: xBondMaterials,
    askPrompt: 'Walk me through the X-Bond over tile detail and prep requirements.',
    layers: detailLayers,
    steps: defaultSteps,
  },
  {
    id: 'wood-deck-detail',
    title: 'Wood / Plywood Detail',
    subtitle: 'Wood, plywood, and OSB deck build-up',
    category: 'X-Bond',
    summary: 'Official wood detail for stable plywood or OSB substrates before X-Bond finish work.',
    sourceDocument: 'Wood-Detail.pdf',
    sourcePage: 'Official wood detail',
    materials: xBondMaterials,
    askPrompt: 'Walk me through the X-Bond wood or plywood detail.',
    layers: detailLayers,
    steps: defaultSteps,
  },
  {
    id: 'wall-detail',
    title: 'Wall Detail',
    subtitle: 'Vertical X-Bond wall build-up',
    category: 'X-Bond',
    summary: 'Official wall drawing for vertical X-Bond installations.',
    sourceDocument: 'Wall-Detail.pdf',
    sourcePage: 'Official wall detail',
    materials: xBondMaterials,
    askPrompt: 'Explain the Semco wall detail and vertical X-Bond procedure.',
    layers: detailLayers,
    steps: defaultSteps,
  },
  {
    id: 'shower-detail-concrete',
    title: 'Shower Detail - Concrete',
    subtitle: 'Wet-area build-up over concrete',
    category: 'Wet Area',
    summary: 'Concrete shower detail showing wet-area waterproofing and X-Bond layers.',
    sourceDocument: 'Shower-Detail-Concrete.pdf',
    sourcePage: 'Official shower detail',
    materials: waterproofingMaterials,
    askPrompt: 'Explain the Semco shower detail over concrete.',
    layers: detailLayers,
    steps: defaultSteps,
  },
  {
    id: 'shower-detail-wood',
    title: 'Shower Detail - Wood',
    subtitle: 'Wet-area build-up over wood',
    category: 'Wet Area',
    summary: 'Wood shower detail showing membrane/fabric requirements before finish layers.',
    sourceDocument: 'Shower-Detail-Wood.pdf',
    sourcePage: 'Official shower detail',
    materials: waterproofingMaterials,
    askPrompt: 'Explain the Semco shower detail over wood.',
    layers: detailLayers,
    steps: defaultSteps,
  },
  {
    id: 'shower-detail-glasroc-osb',
    title: 'Shower Detail - Glasroc / OSB',
    subtitle: 'Wet-area build-up over glasroc, plywood, or OSB',
    category: 'Wet Area',
    summary: 'Official shower detail showing X-Bond over glasroc, plywood, or OSB boards with Liquid Membrane fabric reinforcement at joints and inside corners.',
    sourceDocument: 'Shower-Detail-Glasroc-OSB.pdf',
    sourcePage: 'Official shower detail',
    materials: waterproofingMaterials,
    askPrompt: 'Explain the Semco shower detail over glasroc, plywood, or OSB boards.',
    layers: detailLayers,
    steps: [
      'Confirm the board substrate is sound, fastened, stable, clean, and dry enough for coating.',
      'Apply SEMCO Liquid Membrane with fabric reinforcement at joints and inside corners.',
      'Install the X-Bond scratch coat over the prepared and reinforced substrate.',
      'Use Brown Coat only where optional build, leveling, or void filling is required by the project detail.',
      'Apply the X-Bond Seamless Stone finish and seal with the specified stocked Semco sealer.',
    ],
  },
  {
    id: 'shower-drain-detail',
    title: 'Shower Drain Detail',
    subtitle: 'Drain transition and waterproofing detail',
    category: 'Wet Area',
    summary: 'Official drain detail for controlling water-risk transitions in showers.',
    sourceDocument: 'Shower-Drain-Detail.pdf',
    sourcePage: 'Official drain detail',
    materials: waterproofingMaterials,
    askPrompt: 'Explain how to detail a shower drain with Semco materials.',
    layers: detailLayers,
    steps: defaultSteps,
  },
  {
    id: 'cove-base-detail',
    title: 'Cove Base Detail',
    subtitle: 'Wall-to-floor transition detail',
    category: 'Details',
    summary: 'Official drawing for cove base transitions and inside corners.',
    sourceDocument: 'Cove-Base-Detail.pdf',
    sourcePage: 'Official cove detail',
    materials: xBondMaterials,
    askPrompt: 'Explain the Semco cove base detail.',
    layers: detailLayers,
    steps: defaultSteps,
  },
  {
    id: 'cove-base-plywood-detail',
    title: 'Cove Base - Plywood',
    subtitle: 'Wood substrate cove transition',
    category: 'Details',
    summary: 'Official cove detail for plywood/wood transitions.',
    sourceDocument: 'Cove-Base-Detail-Plywood.pdf',
    sourcePage: 'Official cove detail',
    materials: xBondMaterials,
    askPrompt: 'Explain the plywood cove base detail.',
    layers: detailLayers,
    steps: defaultSteps,
  },
  {
    id: 'drain-detail',
    title: 'Drain Detail',
    subtitle: 'Floor drain waterproofing transition',
    category: 'Details',
    summary: 'Official drawing for drain transitions inside the Semco build-up.',
    sourceDocument: 'Drain-Detail.pdf',
    sourcePage: 'Official drain detail',
    materials: waterproofingMaterials,
    askPrompt: 'Explain the Semco drain detail.',
    layers: detailLayers,
    steps: defaultSteps,
  },
  {
    id: 'stair-detail',
    title: 'Stair Detail',
    subtitle: 'X-Bond stair layer sequence',
    category: 'Details',
    summary: 'Official stair drawing for X-Bond work on steps and edges.',
    sourceDocument: 'Stair-Detail.pdf',
    sourcePage: 'Official stair detail',
    materials: xBondMaterials,
    askPrompt: 'Explain the Semco stair detail.',
    layers: detailLayers,
    steps: defaultSteps,
  },
  {
    id: 'pool-deck-resurfacing',
    title: 'Pool Deck Resurfacing',
    subtitle: 'Exterior pool deck detail',
    category: 'Pool',
    summary: 'Official pool deck resurfacing drawing for exterior concrete around pools.',
    sourceDocument: 'Pool-Deck-Resurfacing-Detail.pdf',
    sourcePage: 'Official pool deck detail',
    materials: waterproofingMaterials,
    askPrompt: 'Explain the pool deck resurfacing detail.',
    layers: detailLayers,
    steps: defaultSteps,
  },
  {
    id: 'pool-resurfacing-below-grade',
    title: 'Pool / Below-Grade Detail',
    subtitle: 'Interior pool or below-grade resurfacing',
    category: 'Pool',
    summary: 'Official pool resurfacing and below-grade drawing for water containment work.',
    sourceDocument: 'Pool-Resurfacing-Detail-Interior-Below-Grade.pdf',
    sourcePage: 'Official pool detail',
    materials: waterproofingMaterials,
    askPrompt: 'Explain the pool resurfacing and below-grade detail.',
    layers: detailLayers,
    steps: defaultSteps,
  },
  {
    id: 'basement-waterproofing-x-bond',
    title: 'Basement Waterproofing X-Bond',
    subtitle: 'Below-grade waterproofing with X-Bond',
    category: 'Waterproofing',
    summary: 'Official basement waterproofing X-Bond detail for below-grade concrete.',
    sourceDocument: 'Basement-Waterproofing-X-Bond.pdf',
    sourcePage: 'Official basement detail',
    materials: waterproofingMaterials,
    askPrompt: 'Explain the basement waterproofing X-Bond detail.',
    layers: detailLayers,
    steps: defaultSteps,
  },
  {
    id: 'liquid-membrane-over-concrete',
    title: 'Liquid Membrane Over Concrete',
    subtitle: 'Membrane detail over concrete',
    category: 'Waterproofing',
    summary: 'Official Liquid Membrane drawing for prepared concrete.',
    sourceDocument: 'LM-over-concrete.pdf',
    sourcePage: 'Official membrane detail',
    materials: waterproofingMaterials,
    askPrompt: 'Explain the Liquid Membrane over concrete detail.',
    layers: detailLayers,
    steps: defaultSteps,
  },
  {
    id: 'liquid-membrane-over-gypcrete',
    title: 'Liquid Membrane Over Gyp-Crete',
    subtitle: 'Membrane detail over gyp-crete',
    category: 'Waterproofing',
    summary: 'Official Liquid Membrane drawing for gyp-crete assemblies.',
    sourceDocument: 'LM-over-Gyp-crete.pdf',
    sourcePage: 'Official membrane detail',
    materials: waterproofingMaterials,
    askPrompt: 'Explain the Liquid Membrane over gyp-crete detail.',
    layers: detailLayers,
    steps: defaultSteps,
  },
  {
    id: 'waterproofing-metal',
    title: 'Waterproofing Metal',
    subtitle: 'Metal substrate waterproofing detail',
    category: 'Waterproofing',
    summary: 'Official waterproofing drawing for properly prepared metal substrates.',
    sourceDocument: 'Waterproofing-Metal.pdf',
    sourcePage: 'Official metal detail',
    materials: waterproofingMaterials,
    askPrompt: 'Explain the waterproofing metal detail.',
    layers: detailLayers,
    steps: defaultSteps,
  },
  {
    id: 'ada-mma-system-steps',
    title: 'ADA MMA System Steps',
    subtitle: 'Official X-Bond ADA MMA sequence',
    category: 'Steps',
    summary: 'Official step drawing for the ADA MMA X-Bond system.',
    sourceDocument: 'ADA-MMA-System-Steps.pdf',
    sourcePage: 'Official steps',
    materials: xBondMaterials,
    askPrompt: 'Explain the ADA MMA system steps.',
    layers: detailLayers,
    steps: defaultSteps,
  },
  {
    id: 'broadcast-system-steps',
    title: 'Broadcast System Steps',
    subtitle: 'Official X-Bond broadcast sequence',
    category: 'Steps',
    summary: 'Official step drawing for the X-Bond broadcast system.',
    sourceDocument: 'Broadcast-System-Steps.pdf',
    sourcePage: 'Official steps',
    materials: xBondMaterials,
    askPrompt: 'Explain the Broadcast system steps.',
    layers: detailLayers,
    steps: defaultSteps,
  },
  {
    id: 'color-bond-steps',
    title: 'Color Bond Steps',
    subtitle: 'Official color bond sequence',
    category: 'Steps',
    summary: 'Official step drawing for Color Bond over X-Bond Seamless Stone.',
    sourceDocument: 'Color-Bond-Steps.pdf',
    sourcePage: 'Official steps',
    materials: xBondMaterials,
    askPrompt: 'Explain the Color Bond steps.',
    layers: detailLayers,
    steps: defaultSteps,
  },
  {
    id: 'polished-bond-steps',
    title: 'Polished Bond Steps',
    subtitle: 'Official polished bond sequence',
    category: 'Steps',
    summary: 'Official step drawing for Polished Bond / smoother finish work.',
    sourceDocument: 'Polished-Bond-Steps.pdf',
    sourcePage: 'Official steps',
    materials: ['X-Bond Liquid', 'MicroBond', 'Sealer'],
    askPrompt: 'Explain the Polished Bond steps.',
    layers: detailLayers,
    steps: defaultSteps,
  },
  {
    id: 'ceiling-surface-steps',
    title: 'Ceiling Surface Steps',
    subtitle: 'Official ceiling surface sequence',
    category: 'Steps',
    summary: 'Official step drawing for ceiling surface work.',
    sourceDocument: 'Ceiling-Surface-Steps.pdf',
    sourcePage: 'Official steps',
    materials: xBondMaterials,
    askPrompt: 'Explain the ceiling surface steps.',
    layers: detailLayers,
    steps: defaultSteps,
  },
];
